name: mod_slg2_v2

hidden_dim: 32
num_heads: 2
num_layers_transformer: 3
dropout: 0
num_layers_ffn: 3
# use_batchnorm: True
hidden_dim_1: 16
num_layers1: 2
edge_node_hidden_dim: 32
n_layers_ff_ef: 2
only_last_h: True
include_topological_features: True
